# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'arayuz.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 528)
        MainWindow.setMouseTracking(True)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.kamera_frame = QtWidgets.QFrame(self.centralwidget)
        self.kamera_frame.setGeometry(QtCore.QRect(160, 70, 481, 291))
        self.kamera_frame.setMaximumSize(QtCore.QSize(1400, 800))
        self.kamera_frame.setStyleSheet("background-color: black;\n"
"border-radius: 15px;")
        self.kamera_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.kamera_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.kamera_frame.setObjectName("kamera_frame")
        self.yatay_hiz_widget = QtWidgets.QWidget(self.centralwidget)
        self.yatay_hiz_widget.setGeometry(QtCore.QRect(10, 20, 141, 141))
        self.yatay_hiz_widget.setMinimumSize(QtCore.QSize(0, 0))
        self.yatay_hiz_widget.setMaximumSize(QtCore.QSize(250, 250))
        self.yatay_hiz_widget.setStyleSheet("border-radius: 150%;\n"
"")
        self.yatay_hiz_widget.setObjectName("yatay_hiz_widget")
        self.altimetre_widget = QtWidgets.QWidget(self.centralwidget)
        self.altimetre_widget.setGeometry(QtCore.QRect(650, 20, 141, 141))
        self.altimetre_widget.setMinimumSize(QtCore.QSize(0, 0))
        self.altimetre_widget.setMaximumSize(QtCore.QSize(250, 250))
        self.altimetre_widget.setStyleSheet("\n"
"border-radius: 150%;")
        self.altimetre_widget.setObjectName("altimetre_widget")
        self.ufuk_widget = QtWidgets.QWidget(self.centralwidget)
        self.ufuk_widget.setGeometry(QtCore.QRect(10, 170, 141, 141))
        self.ufuk_widget.setMinimumSize(QtCore.QSize(0, 0))
        self.ufuk_widget.setMaximumSize(QtCore.QSize(250, 250))
        self.ufuk_widget.setStyleSheet("\n"
"border-radius: 150%;")
        self.ufuk_widget.setObjectName("ufuk_widget")
        self.pusula_widget = QtWidgets.QWidget(self.centralwidget)
        self.pusula_widget.setGeometry(QtCore.QRect(650, 170, 141, 141))
        self.pusula_widget.setMinimumSize(QtCore.QSize(0, 0))
        self.pusula_widget.setMaximumSize(QtCore.QSize(250, 250))
        self.pusula_widget.setStyleSheet("\n"
"border-radius: 150%; ")
        self.pusula_widget.setObjectName("pusula_widget")
        self.dikey_hiz_widget = QtWidgets.QWidget(self.centralwidget)
        self.dikey_hiz_widget.setGeometry(QtCore.QRect(10, 320, 141, 141))
        self.dikey_hiz_widget.setMinimumSize(QtCore.QSize(0, 0))
        self.dikey_hiz_widget.setMaximumSize(QtCore.QSize(250, 250))
        self.dikey_hiz_widget.setStyleSheet("\n"
"border-radius: 150%;")
        self.dikey_hiz_widget.setObjectName("dikey_hiz_widget")
        self.groundspeed_widget = QtWidgets.QWidget(self.centralwidget)
        self.groundspeed_widget.setGeometry(QtCore.QRect(650, 320, 141, 141))
        self.groundspeed_widget.setMinimumSize(QtCore.QSize(0, 0))
        self.groundspeed_widget.setMaximumSize(QtCore.QSize(250, 250))
        self.groundspeed_widget.setMouseTracking(True)
        self.groundspeed_widget.setStyleSheet("\n"
"border-radius: 150%;")
        self.groundspeed_widget.setObjectName("groundspeed_widget")
        self.adress_combo = QtWidgets.QComboBox(self.centralwidget)
        self.adress_combo.setGeometry(QtCore.QRect(160, 10, 151, 21))
        self.adress_combo.setMinimumSize(QtCore.QSize(0, 0))
        self.adress_combo.setMaximumSize(QtCore.QSize(235345, 16777215))
        self.adress_combo.setSizeIncrement(QtCore.QSize(140, 0))
        self.adress_combo.setStyleSheet("QComboBox {\n"
"    background-color: #77a1e2; /* Arkaplan rengi */\n"
"    border: 1px solid #ccc; /* Kenarlık */\n"
"    border-radius: 4px; /* Kenar yarıçapı */\n"
"    width: 180px;\n"
"    height: 50px;\n"
"    border-radius: 10%;\n"
"    font: 75 12pt \"MS Shell Dlg 2\";\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    image: url(contents/down-chevron.png); /* Aşağı ok görseli */\n"
"    padding-right: 15px;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    border: none; /* Kenarlık yok */\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    background-color: #fff; /* Açılır menü arkaplan rengi */\n"
"    border: 1px solid #ccc; /* Açılır menü kenarlık */\n"
"    selection-background-color: #007acc; /* Seçili öğe arkaplan rengi */\n"
"    color: #000; /* Metin rengi */\n"
"}\n"
"")
        self.adress_combo.setObjectName("adress_combo")
        self.adress_combo.addItem("")
        self.baud_combo = QtWidgets.QComboBox(self.centralwidget)
        self.baud_combo.setGeometry(QtCore.QRect(160, 40, 151, 21))
        self.baud_combo.setMinimumSize(QtCore.QSize(0, 0))
        self.baud_combo.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.baud_combo.setSizeIncrement(QtCore.QSize(140, 0))
        self.baud_combo.setStyleSheet("QComboBox {\n"
"    background-color: #77a1e2; /* Arkaplan rengi */\n"
"    border: 1px solid #ccc; /* Kenarlık */\n"
"    border-radius: 4px; /* Kenar yarıçapı */\n"
"    width: 180px;\n"
"    height: 50px;\n"
"    border-radius: 10%;\n"
"    font: 75 12pt \"MS Shell Dlg 2\";\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    image: url(contents/down-chevron.png); /* Aşağı ok görseli */\n"
"    padding-right: 15px;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    border: none; /* Kenarlık yok */\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    background-color: #fff; /* Açılır menü arkaplan rengi */\n"
"    border: 1px solid #ccc; /* Açılır menü kenarlık */\n"
"    selection-background-color: #007acc; /* Seçili öğe arkaplan rengi */\n"
"    color: #000; /* Metin rengi */\n"
"}\n"
"")
        self.baud_combo.setObjectName("baud_combo")
        self.baud_combo.addItem("")
        self.btnRTL = QtWidgets.QPushButton(self.centralwidget)
        self.btnRTL.setGeometry(QtCore.QRect(340, 420, 121, 41))
        self.btnRTL.setStyleSheet("QPushButton {\n"
"    background-color: rgb(255, 37, 53); /* Arkaplan rengi */\n"
"    color: white; /* Metin rengi */\n"
"    text-align: center; /* Metni merkezle */\n"
"    text-decoration: none; /* Altçizgiyi kaldır */\n"
"    font-size: 16px; /* Metin boyutu */\n"
"    border-radius: 8px; /* Kenar yarıçapı */\n"
"    \n"
"    font: 75 13pt \"MS Shell Dlg 2\";\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(192, 28, 40); /* Fare üzerine gelindiğinde arkaplan rengi */\n"
"    color: white; /* Fare üzerine gelindiğinde metin rengi */\n"
"}")
        self.btnRTL.setObjectName("btnRTL")
        self.btnBaslat = QtWidgets.QPushButton(self.centralwidget)
        self.btnBaslat.setGeometry(QtCore.QRect(520, 20, 121, 41))
        self.btnBaslat.setStyleSheet("QPushButton {\n"
"    background-color: #55c65a; /* Arkaplan rengi */\n"
"    color: white; /* Metin rengi */\n"
"    text-align: center; /* Metni merkezle */\n"
"    text-decoration: none; /* Altçizgiyi kaldır */\n"
"    font-size: 16px; /* Metin boyutu */\n"
"    border-radius: 8px; /* Kenar yarıçapı */\n"
"    \n"
"    font-size: 13pt;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #45a049; /* Fare üzerine gelindiğinde arkaplan rengi */\n"
"    color: white; /* Fare üzerine gelindiğinde metin rengi */\n"
"}")
        self.btnBaslat.setObjectName("btnBaslat")
        self.btnConnect = QtWidgets.QPushButton(self.centralwidget)
        self.btnConnect.setGeometry(QtCore.QRect(440, 20, 71, 41))
        self.btnConnect.setStyleSheet("QPushButton {\n"
"    background-color: #55c65a; /* Arkaplan rengi */\n"
"    color: white; /* Metin rengi */\n"
"    text-align: center; /* Metni merkezle */\n"
"    text-decoration: none; /* Altçizgiyi kaldır */\n"
"    font-size: 16px; /* Metin boyutu */\n"
"    border-radius: 8px; /* Kenar yarıçapı */\n"
"    \n"
"    font-size: 13pt;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #45a049; /* Fare üzerine gelindiğinde arkaplan rengi */\n"
"    color: white; /* Fare üzerine gelindiğinde metin rengi */\n"
"}")
        self.btnConnect.setObjectName("btnConnect")
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setGeometry(QtCore.QRect(160, 370, 171, 41))
        self.groupBox_4.setMinimumSize(QtCore.QSize(120, 0))
        self.groupBox_4.setStyleSheet("background-color: #27354a;\n"
"border-radius: 15%;\n"
"border: 1px solid;")
        self.groupBox_4.setTitle("")
        self.groupBox_4.setObjectName("groupBox_4")
        self.lblMevcutWaypoint_2 = QtWidgets.QLabel(self.groupBox_4)
        self.lblMevcutWaypoint_2.setGeometry(QtCore.QRect(130, 10, 31, 20))
        self.lblMevcutWaypoint_2.setStyleSheet("border: none;\n"
"font: 75 12pt \"MS Shell Dlg 2\";\n"
"color: white;")
        self.lblMevcutWaypoint_2.setObjectName("lblMevcutWaypoint_2")
        self.label_9 = QtWidgets.QLabel(self.groupBox_4)
        self.label_9.setGeometry(QtCore.QRect(10, 10, 111, 20))
        self.label_9.setStyleSheet("border: none;\n"
"color: #1bb575;\n"
"font-size: 10pt;")
        self.label_9.setObjectName("label_9")
        self.label_9.raise_()
        self.lblMevcutWaypoint_2.raise_()
        self.groupBox_7 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_7.setGeometry(QtCore.QRect(470, 370, 171, 41))
        self.groupBox_7.setMinimumSize(QtCore.QSize(120, 0))
        self.groupBox_7.setStyleSheet("background-color: #27354a;\n"
"border-radius: 15%;\n"
"border: 1px solid;")
        self.groupBox_7.setTitle("")
        self.groupBox_7.setObjectName("groupBox_7")
        self.label_25 = QtWidgets.QLabel(self.groupBox_7)
        self.label_25.setGeometry(QtCore.QRect(10, 10, 131, 20))
        self.label_25.setStyleSheet("border: none;\n"
"color: #1bb575;\n"
"font-size: 10pt;")
        self.label_25.setObjectName("label_25")
        self.lblKalanMesafe = QtWidgets.QLabel(self.groupBox_7)
        self.lblKalanMesafe.setGeometry(QtCore.QRect(110, 10, 51, 21))
        self.lblKalanMesafe.setStyleSheet("border: none;\n"
"font: 75 12pt \"MS Shell Dlg 2\";\n"
"color: white;")
        self.lblKalanMesafe.setObjectName("lblKalanMesafe")
        self.btnUcusPlani_2 = QtWidgets.QPushButton(self.groupBox_7)
        self.btnUcusPlani_2.setGeometry(QtCore.QRect(-260, 0, 111, 41))
        self.btnUcusPlani_2.setStyleSheet("QPushButton {\n"
"    background-color: #4CAF50; /* Arkaplan rengi */\n"
"    color: white; /* Metin rengi */\n"
"    text-align: center; /* Metni merkezle */\n"
"    text-decoration: none; /* Altçizgiyi kaldır */\n"
"    font-size: 16px; /* Metin boyutu */\n"
"    border-radius: 8px; /* Kenar yarıçapı */\n"
"    \n"
"    font: 75 14pt \"MS Shell Dlg 2\";\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #45a049; /* Fare üzerine gelindiğinde arkaplan rengi */\n"
"    color: white; /* Fare üzerine gelindiğinde metin rengi */\n"
"}")
        self.btnUcusPlani_2.setObjectName("btnUcusPlani_2")
        self.label_10 = QtWidgets.QLabel(self.groupBox_7)
        self.label_10.setGeometry(QtCore.QRect(-130, 0, 101, 21))
        self.label_10.setStyleSheet("border: none;\n"
"color: #1bb575;\n"
"font: 75 10pt \"MS Shell Dlg 2\";")
        self.label_10.setObjectName("label_10")
        self.label_25.raise_()
        self.btnUcusPlani_2.raise_()
        self.label_10.raise_()
        self.lblKalanMesafe.raise_()
        self.lblDurum = QtWidgets.QLabel(self.centralwidget)
        self.lblDurum.setGeometry(QtCore.QRect(160, 420, 171, 41))
        self.lblDurum.setMinimumSize(QtCore.QSize(120, 0))
        self.lblDurum.setStyleSheet("font-size: 12pt;\n"
"color: #1bb575;\n"
"background: rgb(39, 53, 74);\n"
"border: 1px solid;\n"
"border-radius: 15%;")
        self.lblDurum.setAlignment(QtCore.Qt.AlignCenter)
        self.lblDurum.setObjectName("lblDurum")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(320, 20, 111, 41))
        self.groupBox_3.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox_3.setStyleSheet("background-color: #27354a;\n"
"border-radius: 15%;\n"
"border: 1px solid;\n"
"")
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.label_5 = QtWidgets.QLabel(self.groupBox_3)
        self.label_5.setGeometry(QtCore.QRect(10, 10, 61, 20))
        self.label_5.setStyleSheet("border: none;\n"
"color: #1bb575;\n"
"font-size: 10pt;")
        self.label_5.setObjectName("label_5")
        self.lblBatarya = QtWidgets.QLabel(self.groupBox_3)
        self.lblBatarya.setGeometry(QtCore.QRect(70, 10, 31, 21))
        self.lblBatarya.setStyleSheet("border: none;\n"
"font: 75 11pt \"MS Shell Dlg 2\";\n"
"color: white;")
        self.lblBatarya.setObjectName("lblBatarya")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(470, 420, 171, 41))
        self.groupBox_2.setMinimumSize(QtCore.QSize(100, 0))
        self.groupBox_2.setStyleSheet("background-color: #27354a;\n"
"border-radius: 15%;\n"
"border: 1px solid;")
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 91, 20))
        self.label_2.setStyleSheet("border: none;\n"
"color: #1bb575;\n"
"font-size: 10pt;")
        self.label_2.setObjectName("label_2")
        self.lblMOD = QtWidgets.QLabel(self.groupBox_2)
        self.lblMOD.setGeometry(QtCore.QRect(90, 10, 71, 21))
        self.lblMOD.setStyleSheet("border: none;\n"
"font: 75 11pt \"MS Shell Dlg 2\";\n"
"color: white;")
        self.lblMOD.setObjectName("lblMOD")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Ana Sayfa"))
        self.adress_combo.setItemText(0, _translate("MainWindow", "127.0.0.1:14550"))
        self.baud_combo.setItemText(0, _translate("MainWindow", "57600"))
        self.btnRTL.setText(_translate("MainWindow", "RTL"))
        self.btnBaslat.setText(_translate("MainWindow", "Görevi Başlat"))
        self.btnConnect.setText(_translate("MainWindow", "Bağlan"))
        self.lblMevcutWaypoint_2.setText(_translate("MainWindow", "-"))
        self.label_9.setText(_translate("MainWindow", "Mevcut Waypoint"))
        self.label_25.setText(_translate("MainWindow", "Kalan Mesafe"))
        self.lblKalanMesafe.setText(_translate("MainWindow", "-"))
        self.btnUcusPlani_2.setText(_translate("MainWindow", "Uçuş Planı"))
        self.label_10.setText(_translate("MainWindow", "Mevcut Waypoint"))
        self.lblDurum.setText(_translate("MainWindow", "Bağlantı Bekleniyor"))
        self.label_5.setText(_translate("MainWindow", "Batarya"))
        self.lblBatarya.setText(_translate("MainWindow", "-"))
        self.label_2.setText(_translate("MainWindow", "Uçuş Modu"))
        self.lblMOD.setText(_translate("MainWindow", "-"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
