# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ayarlar.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Ayarlar(object):
    def setupUi(self, Ayarlar):
        Ayarlar.setObjectName("Ayarlar")
        Ayarlar.resize(493, 480)
        Ayarlar.setStyleSheet("background: rgb(20, 24, 36)")
        self.frame_5 = QtWidgets.QFrame(Ayarlar)
        self.frame_5.setGeometry(QtCore.QRect(10, 20, 471, 461))
        self.frame_5.setStyleSheet("border: 1px solid\n"
"")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.frame = QtWidgets.QFrame(self.frame_5)
        self.frame.setGeometry(QtCore.QRect(30, 60, 201, 111))
        self.frame.setStyleSheet("border: 1px solid\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.kose1lat = QtWidgets.QLineEdit(self.frame)
        self.kose1lat.setGeometry(QtCore.QRect(10, 10, 181, 41))
        self.kose1lat.setStyleSheet("border: none;\n"
"background-color: white; /* Arkaplan rengi */\n"
"border: 4px solid #ccc; /* Kenarlık */\n"
"border-radius: 4px; /* Kenar yarıçapı */\n"
"padding: 1px 18px 1px 3px; /* İç boşluk */\n"
"border-radius: 10%;\n"
"font: 75 12pt \"MS Shell Dlg 2\";")
        self.kose1lat.setObjectName("kose1lat")
        self.kose1lon = QtWidgets.QLineEdit(self.frame)
        self.kose1lon.setGeometry(QtCore.QRect(10, 59, 181, 41))
        self.kose1lon.setStyleSheet("border: none;\n"
"background-color: white; /* Arkaplan rengi */\n"
"border: 4px solid #ccc; /* Kenarlık */\n"
"border-radius: 4px; /* Kenar yarıçapı */\n"
"padding: 1px 18px 1px 3px; /* İç boşluk */\n"
"border-radius: 10%;\n"
"font: 75 12pt \"MS Shell Dlg 2\";")
        self.kose1lon.setObjectName("kose1lon")
        self.frame_3 = QtWidgets.QFrame(self.frame_5)
        self.frame_3.setGeometry(QtCore.QRect(30, 180, 201, 111))
        self.frame_3.setStyleSheet("border: 1px solid\n"
"")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.kose3lat = QtWidgets.QLineEdit(self.frame_3)
        self.kose3lat.setGeometry(QtCore.QRect(10, 10, 181, 41))
        self.kose3lat.setStyleSheet("border: none;\n"
"background-color: white; /* Arkaplan rengi */\n"
"border: 4px solid #ccc; /* Kenarlık */\n"
"border-radius: 4px; /* Kenar yarıçapı */\n"
"padding: 1px 18px 1px 3px; /* İç boşluk */\n"
"border-radius: 10%;\n"
"font: 75 12pt \"MS Shell Dlg 2\";")
        self.kose3lat.setObjectName("kose3lat")
        self.kose3lon = QtWidgets.QLineEdit(self.frame_3)
        self.kose3lon.setGeometry(QtCore.QRect(10, 60, 181, 41))
        self.kose3lon.setStyleSheet("border: none;\n"
"background-color: white; /* Arkaplan rengi */\n"
"border: 4px solid #ccc; /* Kenarlık */\n"
"border-radius: 4px; /* Kenar yarıçapı */\n"
"padding: 1px 18px 1px 3px; /* İç boşluk */\n"
"border-radius: 10%;\n"
"font: 75 12pt \"MS Shell Dlg 2\";")
        self.kose3lon.setObjectName("kose3lon")
        self.label = QtWidgets.QLabel(self.frame_5)
        self.label.setGeometry(QtCore.QRect(60, 10, 331, 41))
        self.label.setStyleSheet("color: white;\n"
"font: 75 14pt \"MS Shell Dlg 2\";")
        self.label.setObjectName("label")
        self.btnKaydet = QtWidgets.QPushButton(self.frame_5)
        self.btnKaydet.setGeometry(QtCore.QRect(40, 350, 191, 71))
        self.btnKaydet.setStyleSheet("QPushButton {\n"
"    background-color: #4CAF50; /* Arkaplan rengi */\n"
"    border: none; /* Kenarlık yok */\n"
"    color: white; /* Metin rengi */\n"
"    padding: 15px 32px; /* Düğme içeriği arasındaki boşluk */\n"
"    text-align: center; /* Metni merkezle */\n"
"    text-decoration: none; /* Altçizgiyi kaldır */\n"
"    font-size: 16px; /* Metin boyutu */\n"
"    margin: 4px 2px; /* Düğme arasındaki boşluk */\n"
"    border-radius: 8px; /* Kenar yarıçapı */\n"
"    font: 75 16pt \"MS Shell Dlg 2\";\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #45a049; /* Fare üzerine gelindiğinde arkaplan rengi */\n"
"    color: white; /* Fare üzerine gelindiğinde metin rengi */\n"
"}")
        self.btnKaydet.setObjectName("btnKaydet")
        self.frame_2 = QtWidgets.QFrame(self.frame_5)
        self.frame_2.setGeometry(QtCore.QRect(240, 60, 201, 111))
        self.frame_2.setStyleSheet("border: 1px solid\n"
"")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.kose2lat = QtWidgets.QLineEdit(self.frame_2)
        self.kose2lat.setGeometry(QtCore.QRect(10, 10, 181, 41))
        self.kose2lat.setStyleSheet("border: none;\n"
"background-color: white; /* Arkaplan rengi */\n"
"border: 4px solid #ccc; /* Kenarlık */\n"
"border-radius: 4px; /* Kenar yarıçapı */\n"
"padding: 1px 18px 1px 3px; /* İç boşluk */\n"
"border-radius: 10%;\n"
"font: 75 12pt \"MS Shell Dlg 2\";")
        self.kose2lat.setObjectName("kose2lat")
        self.kose2lon = QtWidgets.QLineEdit(self.frame_2)
        self.kose2lon.setGeometry(QtCore.QRect(10, 59, 181, 41))
        self.kose2lon.setStyleSheet("border: none;\n"
"background-color: white; /* Arkaplan rengi */\n"
"border: 4px solid #ccc; /* Kenarlık */\n"
"border-radius: 4px; /* Kenar yarıçapı */\n"
"padding: 1px 18px 1px 3px; /* İç boşluk */\n"
"border-radius: 10%;\n"
"font: 75 12pt \"MS Shell Dlg 2\";")
        self.kose2lon.setObjectName("kose2lon")
        self.frame_4 = QtWidgets.QFrame(self.frame_5)
        self.frame_4.setGeometry(QtCore.QRect(240, 180, 201, 111))
        self.frame_4.setStyleSheet("border: 1px solid\n"
"")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.kose4lat = QtWidgets.QLineEdit(self.frame_4)
        self.kose4lat.setGeometry(QtCore.QRect(10, 10, 181, 41))
        self.kose4lat.setStyleSheet("border: none;\n"
"background-color: white; /* Arkaplan rengi */\n"
"border: 4px solid #ccc; /* Kenarlık */\n"
"border-radius: 4px; /* Kenar yarıçapı */\n"
"padding: 1px 18px 1px 3px; /* İç boşluk */\n"
"border-radius: 10%;\n"
"font: 75 12pt \"MS Shell Dlg 2\";")
        self.kose4lat.setObjectName("kose4lat")
        self.kose4lon = QtWidgets.QLineEdit(self.frame_4)
        self.kose4lon.setGeometry(QtCore.QRect(10, 59, 181, 41))
        self.kose4lon.setStyleSheet("border: none;\n"
"background-color: white; /* Arkaplan rengi */\n"
"border: 4px solid #ccc; /* Kenarlık */\n"
"border-radius: 4px; /* Kenar yarıçapı */\n"
"padding: 1px 18px 1px 3px; /* İç boşluk */\n"
"border-radius: 10%;\n"
"font: 75 12pt \"MS Shell Dlg 2\";")
        self.kose4lon.setObjectName("kose4lon")
        self.altitude = QtWidgets.QLineEdit(self.frame_5)
        self.altitude.setGeometry(QtCore.QRect(40, 300, 381, 41))
        self.altitude.setStyleSheet("border: none;\n"
"background-color: white; /* Arkaplan rengi */\n"
"border: 4px solid #ccc; /* Kenarlık */\n"
"border-radius: 4px; /* Kenar yarıçapı */\n"
"padding: 1px 18px 1px 3px; /* İç boşluk */\n"
"border-radius: 10%;\n"
"font: 75 12pt \"MS Shell Dlg 2\";")
        self.altitude.setObjectName("altitude")
        self.btnVarsaylan = QtWidgets.QPushButton(self.frame_5)
        self.btnVarsaylan.setGeometry(QtCore.QRect(230, 350, 191, 71))
        self.btnVarsaylan.setStyleSheet("QPushButton {\n"
"    background-color: #4CAF50; /* Arkaplan rengi */\n"
"    border: none; /* Kenarlık yok */\n"
"    color: white; /* Metin rengi */\n"
"    padding: 15px 32px; /* Düğme içeriği arasındaki boşluk */\n"
"    text-align: center; /* Metni merkezle */\n"
"    text-decoration: none; /* Altçizgiyi kaldır */\n"
"    font-size: 16px; /* Metin boyutu */\n"
"    margin: 4px 2px; /* Düğme arasındaki boşluk */\n"
"    border-radius: 8px; /* Kenar yarıçapı */\n"
"    font: 75 16pt \"MS Shell Dlg 2\";\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #45a049; /* Fare üzerine gelindiğinde arkaplan rengi */\n"
"    color: white; /* Fare üzerine gelindiğinde metin rengi */\n"
"}")
        self.btnVarsaylan.setObjectName("btnVarsaylan")

        self.retranslateUi(Ayarlar)
        QtCore.QMetaObject.connectSlotsByName(Ayarlar)

    def retranslateUi(self, Ayarlar):
        _translate = QtCore.QCoreApplication.translate
        Ayarlar.setWindowTitle(_translate("Ayarlar", "Ayarlar"))
        self.kose1lat.setPlaceholderText(_translate("Ayarlar", "Latitude 1"))
        self.kose1lon.setPlaceholderText(_translate("Ayarlar", "Longitude 1"))
        self.kose3lat.setPlaceholderText(_translate("Ayarlar", "Latitude 3"))
        self.kose3lon.setPlaceholderText(_translate("Ayarlar", "Longitude 3"))
        self.label.setText(_translate("Ayarlar", "Uçuş Alanının Köşe Koordinatları"))
        self.btnKaydet.setText(_translate("Ayarlar", "Kaydet"))
        self.kose2lat.setPlaceholderText(_translate("Ayarlar", "Latitude 2"))
        self.kose2lon.setPlaceholderText(_translate("Ayarlar", "Longitude 2"))
        self.kose4lat.setPlaceholderText(_translate("Ayarlar", "Latitude 4"))
        self.kose4lon.setPlaceholderText(_translate("Ayarlar", "Longitude 4"))
        self.altitude.setPlaceholderText(_translate("Ayarlar", "Uçuş Yüksekliği"))
        self.btnVarsaylan.setText(_translate("Ayarlar", "Varsayılan"))
        
        
        # Varsayılan değerler kolayca deneme yapmak için yazıldı.
        # Horizontal 1
        #self.kose1lat.setText(_translate("Ayarlar", "40.8011906"))
        #self.kose1lon.setText(_translate("Ayarlar", "30.2903165"))
        #self.kose2lat.setText(_translate("Ayarlar", "40.8013561"))
        #self.kose2lon.setText(_translate("Ayarlar", "30.2920666"))
        #self.kose3lat.setText(_translate("Ayarlar", "40.7991531"))
        #self.kose3lon.setText(_translate("Ayarlar", "30.2925441"))
        #self.kose4lat.setText(_translate("Ayarlar", "40.7989886"))
        #self.kose4lon.setText(_translate("Ayarlar", "30.2907711"))
        
        # Horizontal 2
        #self.kose1lat.setText(_translate("Ayarlar", "40.8005561"))
        #self.kose1lon.setText(_translate("Ayarlar", "30.2901220"))
        #self.kose2lat.setText(_translate("Ayarlar", "40.8002962"))
        #self.kose2lon.setText(_translate("Ayarlar", "30.2930832"))
        #self.kose3lat.setText(_translate("Ayarlar", "40.7975023"))
        #self.kose3lon.setText(_translate("Ayarlar", "30.2932978"))
        #self.kose4lat.setText(_translate("Ayarlar", "40.7974861"))
        #self.kose4lon.setText(_translate("Ayarlar", "30.2901220"))
        
        # Vertical 1
        #self.kose1lat.setText(_translate("Ayarlar", "40.8015632"))
        #self.kose1lon.setText(_translate("Ayarlar", "30.2888989"))
        #self.kose2lat.setText(_translate("Ayarlar", "40.8011408"))
        #self.kose2lon.setText(_translate("Ayarlar", "30.2923322"))
        #self.kose3lat.setText(_translate("Ayarlar", "40.7992526"))
        #self.kose3lon.setText(_translate("Ayarlar", "30.2938235"))
        #self.kose4lat.setText(_translate("Ayarlar", "40.7989764"))
        #self.kose4lon.setText(_translate("Ayarlar", "30.2908462"))
        
        # Vertical 2
        self.kose1lat.setText(_translate("Ayarlar", "40.8007266"))
        self.kose1lon.setText(_translate("Ayarlar", "30.2894998"))
        self.kose2lat.setText(_translate("Ayarlar", "40.8011815"))
        self.kose2lon.setText(_translate("Ayarlar", "30.2942312"))
        self.kose3lat.setText(_translate("Ayarlar", "40.7995165"))
        self.kose3lon.setText(_translate("Ayarlar", "30.2946818"))
        self.kose4lat.setText(_translate("Ayarlar", "40.7987937"))
        self.kose4lon.setText(_translate("Ayarlar", "30.2916241"))
        
        self.altitude.setText(_translate("Ayarlar", "100"))

        """
        Turkiye
        1-> 41.876020, 26.667061
        4-> 36.357513, 27.809639
        2-> 41.613714, 42.970772
        3-> 36.991932, 44.157296
        
        Kazimpasa
        1-> 40.8011906, 30.2903165
        2-> 40.8013561, 30.2920666
        3-> 40.7991531, 30.2925441
        4-> 40.7989886, 30.2907711
        """


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Ayarlar = QtWidgets.QWidget()
    ui = Ui_Ayarlar()
    ui.setupUi(Ayarlar)
    Ayarlar.show()
    sys.exit(app.exec_())
