# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Harita.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_harita(object):
    def setupUi(self, harita):
        harita.setObjectName("harita")
        harita.resize(800, 480)
        harita.setStyleSheet("background: rgb(20, 24, 36)")
        self.harita_frame = QtWidgets.QFrame(harita)
        self.harita_frame.setGeometry(QtCore.QRect(0, 7, 800, 471))
        self.harita_frame.setMaximumSize(QtCore.QSize(800, 16777215))
        self.harita_frame.setStyleSheet("border: 1px solid black;\n"
"border-radius: 1%;")
        self.harita_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.harita_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.harita_frame.setObjectName("harita_frame")

        self.retranslateUi(harita)
        QtCore.QMetaObject.connectSlotsByName(harita)

    def retranslateUi(self, harita):
        _translate = QtCore.QCoreApplication.translate
        harita.setWindowTitle(_translate("harita", "Harita"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    harita = QtWidgets.QWidget()
    ui = Ui_harita()
    ui.setupUi(harita)
    harita.show()
    sys.exit(app.exec_())
